# GitHub CI build pipeline
name: Containerapp Preview Extension CI build

on:
  push:
    branches:
      - containerapp-preview-build
    paths:
      - src/containerapp-preview/**
      - .github/workflows/**
  pull_request:
    branches:
      - containerapp-preview-build
    paths:
      - src/containerapp-preview/**
      - .github/workflows/**

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.6"
          - python-version: "3.7"
          - python-version: "3.8"
          - python-version: "3.9"
          - python-version: "3.10"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}


  integration_tests:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/containerapp-preview-build' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "low"
      