name: Build DevContainer

on:
  push:
    branches:
      - containerapp-preview
    paths:
      - .devcontainer/*
      - .github/workflows/devcontainer_build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .devcontainer
          push: true
          tags: ghcr.io/smurawski/az-cli-python-dev:${{ github.sha }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .devcontainer
          push: true
          tags: ghcr.io/smurawski/az-cli-python-dev:latest
